// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.1
// source: arch.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_arch_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_arch_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_arch_proto_rawDescGZIP(), []int{0}
}

type TapeInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *TapeInfoRequest) Reset() {
	*x = TapeInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_arch_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TapeInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TapeInfoRequest) ProtoMessage() {}

func (x *TapeInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_arch_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TapeInfoRequest.ProtoReflect.Descriptor instead.
func (*TapeInfoRequest) Descriptor() ([]byte, []int) {
	return file_arch_proto_rawDescGZIP(), []int{1}
}

func (x *TapeInfoRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type TapeInfoReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Info string `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
}

func (x *TapeInfoReply) Reset() {
	*x = TapeInfoReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_arch_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TapeInfoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TapeInfoReply) ProtoMessage() {}

func (x *TapeInfoReply) ProtoReflect() protoreflect.Message {
	mi := &file_arch_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TapeInfoReply.ProtoReflect.Descriptor instead.
func (*TapeInfoReply) Descriptor() ([]byte, []int) {
	return file_arch_proto_rawDescGZIP(), []int{2}
}

func (x *TapeInfoReply) GetInfo() string {
	if x != nil {
		return x.Info
	}
	return ""
}

type PutObjectReqeust struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Islocal bool   `protobuf:"varint,1,opt,name=islocal,proto3" json:"islocal,omitempty"`
	Srcpath string `protobuf:"bytes,2,opt,name=srcpath,proto3" json:"srcpath,omitempty"`
	Size    int32  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Binary  []byte `protobuf:"bytes,4,opt,name=binary,proto3" json:"binary,omitempty"`
}

func (x *PutObjectReqeust) Reset() {
	*x = PutObjectReqeust{}
	if protoimpl.UnsafeEnabled {
		mi := &file_arch_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PutObjectReqeust) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutObjectReqeust) ProtoMessage() {}

func (x *PutObjectReqeust) ProtoReflect() protoreflect.Message {
	mi := &file_arch_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutObjectReqeust.ProtoReflect.Descriptor instead.
func (*PutObjectReqeust) Descriptor() ([]byte, []int) {
	return file_arch_proto_rawDescGZIP(), []int{3}
}

func (x *PutObjectReqeust) GetIslocal() bool {
	if x != nil {
		return x.Islocal
	}
	return false
}

func (x *PutObjectReqeust) GetSrcpath() string {
	if x != nil {
		return x.Srcpath
	}
	return ""
}

func (x *PutObjectReqeust) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *PutObjectReqeust) GetBinary() []byte {
	if x != nil {
		return x.Binary
	}
	return nil
}

type PutObjectReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Despath string `protobuf:"bytes,1,opt,name=despath,proto3" json:"despath,omitempty"`
}

func (x *PutObjectReply) Reset() {
	*x = PutObjectReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_arch_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PutObjectReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutObjectReply) ProtoMessage() {}

func (x *PutObjectReply) ProtoReflect() protoreflect.Message {
	mi := &file_arch_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutObjectReply.ProtoReflect.Descriptor instead.
func (*PutObjectReply) Descriptor() ([]byte, []int) {
	return file_arch_proto_rawDescGZIP(), []int{4}
}

func (x *PutObjectReply) GetDespath() string {
	if x != nil {
		return x.Despath
	}
	return ""
}

type DmStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Running bool  `protobuf:"varint,1,opt,name=running,proto3" json:"running,omitempty"`
	Pid     int64 `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
}

func (x *DmStatus) Reset() {
	*x = DmStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_arch_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DmStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DmStatus) ProtoMessage() {}

func (x *DmStatus) ProtoReflect() protoreflect.Message {
	mi := &file_arch_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DmStatus.ProtoReflect.Descriptor instead.
func (*DmStatus) Descriptor() ([]byte, []int) {
	return file_arch_proto_rawDescGZIP(), []int{5}
}

func (x *DmStatus) GetRunning() bool {
	if x != nil {
		return x.Running
	}
	return false
}

func (x *DmStatus) GetPid() int64 {
	if x != nil {
		return x.Pid
	}
	return 0
}

type PoolName struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *PoolName) Reset() {
	*x = PoolName{}
	if protoimpl.UnsafeEnabled {
		mi := &file_arch_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PoolName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoolName) ProtoMessage() {}

func (x *PoolName) ProtoReflect() protoreflect.Message {
	mi := &file_arch_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoolName.ProtoReflect.Descriptor instead.
func (*PoolName) Descriptor() ([]byte, []int) {
	return file_arch_proto_rawDescGZIP(), []int{6}
}

func (x *PoolName) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type PoolInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PoolName string `protobuf:"bytes,1,opt,name=poolName,proto3" json:"poolName,omitempty"`
	Total    uint64 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Free     uint64 `protobuf:"varint,3,opt,name=free,proto3" json:"free,omitempty"`
	Unref    uint64 `protobuf:"varint,4,opt,name=unref,proto3" json:"unref,omitempty"`
	Numtapes uint64 `protobuf:"varint,5,opt,name=numtapes,proto3" json:"numtapes,omitempty"`
}

func (x *PoolInfo) Reset() {
	*x = PoolInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_arch_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PoolInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoolInfo) ProtoMessage() {}

func (x *PoolInfo) ProtoReflect() protoreflect.Message {
	mi := &file_arch_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoolInfo.ProtoReflect.Descriptor instead.
func (*PoolInfo) Descriptor() ([]byte, []int) {
	return file_arch_proto_rawDescGZIP(), []int{7}
}

func (x *PoolInfo) GetPoolName() string {
	if x != nil {
		return x.PoolName
	}
	return ""
}

func (x *PoolInfo) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *PoolInfo) GetFree() uint64 {
	if x != nil {
		return x.Free
	}
	return 0
}

func (x *PoolInfo) GetUnref() uint64 {
	if x != nil {
		return x.Unref
	}
	return 0
}

func (x *PoolInfo) GetNumtapes() uint64 {
	if x != nil {
		return x.Numtapes
	}
	return 0
}

type PoolsInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pools []*PoolInfo `protobuf:"bytes,1,rep,name=pools,proto3" json:"pools,omitempty"`
}

func (x *PoolsInfo) Reset() {
	*x = PoolsInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_arch_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PoolsInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoolsInfo) ProtoMessage() {}

func (x *PoolsInfo) ProtoReflect() protoreflect.Message {
	mi := &file_arch_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoolsInfo.ProtoReflect.Descriptor instead.
func (*PoolsInfo) Descriptor() ([]byte, []int) {
	return file_arch_proto_rawDescGZIP(), []int{8}
}

func (x *PoolsInfo) GetPools() []*PoolInfo {
	if x != nil {
		return x.Pools
	}
	return nil
}

type DriverInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DevName string `protobuf:"bytes,2,opt,name=devName,proto3" json:"devName,omitempty"`
	Slot    uint64 `protobuf:"varint,3,opt,name=slot,proto3" json:"slot,omitempty"`
	Status  string `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Busy    bool   `protobuf:"varint,5,opt,name=busy,proto3" json:"busy,omitempty"`
}

func (x *DriverInfo) Reset() {
	*x = DriverInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_arch_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DriverInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverInfo) ProtoMessage() {}

func (x *DriverInfo) ProtoReflect() protoreflect.Message {
	mi := &file_arch_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverInfo.ProtoReflect.Descriptor instead.
func (*DriverInfo) Descriptor() ([]byte, []int) {
	return file_arch_proto_rawDescGZIP(), []int{9}
}

func (x *DriverInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DriverInfo) GetDevName() string {
	if x != nil {
		return x.DevName
	}
	return ""
}

func (x *DriverInfo) GetSlot() uint64 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *DriverInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DriverInfo) GetBusy() bool {
	if x != nil {
		return x.Busy
	}
	return false
}

type DriversInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Drivers []*DriverInfo `protobuf:"bytes,1,rep,name=drivers,proto3" json:"drivers,omitempty"`
}

func (x *DriversInfo) Reset() {
	*x = DriversInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_arch_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DriversInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriversInfo) ProtoMessage() {}

func (x *DriversInfo) ProtoReflect() protoreflect.Message {
	mi := &file_arch_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriversInfo.ProtoReflect.Descriptor instead.
func (*DriversInfo) Descriptor() ([]byte, []int) {
	return file_arch_proto_rawDescGZIP(), []int{10}
}

func (x *DriversInfo) GetDrivers() []*DriverInfo {
	if x != nil {
		return x.Drivers
	}
	return nil
}

type TapeInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Slot        uint64 `protobuf:"varint,2,opt,name=slot,proto3" json:"slot,omitempty"`
	Totalcap    uint64 `protobuf:"varint,3,opt,name=totalcap,proto3" json:"totalcap,omitempty"`
	Remaincap   uint64 `protobuf:"varint,4,opt,name=remaincap,proto3" json:"remaincap,omitempty"`
	Reclaimable uint64 `protobuf:"varint,5,opt,name=reclaimable,proto3" json:"reclaimable,omitempty"`
	Status      string `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Inprogress  uint64 `protobuf:"varint,7,opt,name=inprogress,proto3" json:"inprogress,omitempty"`
	Pool        string `protobuf:"bytes,8,opt,name=pool,proto3" json:"pool,omitempty"`
	State       string `protobuf:"bytes,9,opt,name=state,proto3" json:"state,omitempty"`
}

func (x *TapeInfo) Reset() {
	*x = TapeInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_arch_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TapeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TapeInfo) ProtoMessage() {}

func (x *TapeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_arch_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TapeInfo.ProtoReflect.Descriptor instead.
func (*TapeInfo) Descriptor() ([]byte, []int) {
	return file_arch_proto_rawDescGZIP(), []int{11}
}

func (x *TapeInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TapeInfo) GetSlot() uint64 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *TapeInfo) GetTotalcap() uint64 {
	if x != nil {
		return x.Totalcap
	}
	return 0
}

func (x *TapeInfo) GetRemaincap() uint64 {
	if x != nil {
		return x.Remaincap
	}
	return 0
}

func (x *TapeInfo) GetReclaimable() uint64 {
	if x != nil {
		return x.Reclaimable
	}
	return 0
}

func (x *TapeInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TapeInfo) GetInprogress() uint64 {
	if x != nil {
		return x.Inprogress
	}
	return 0
}

func (x *TapeInfo) GetPool() string {
	if x != nil {
		return x.Pool
	}
	return ""
}

func (x *TapeInfo) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type TapesInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tapes []*TapeInfo `protobuf:"bytes,1,rep,name=tapes,proto3" json:"tapes,omitempty"`
}

func (x *TapesInfo) Reset() {
	*x = TapesInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_arch_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TapesInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TapesInfo) ProtoMessage() {}

func (x *TapesInfo) ProtoReflect() protoreflect.Message {
	mi := &file_arch_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TapesInfo.ProtoReflect.Descriptor instead.
func (*TapesInfo) Descriptor() ([]byte, []int) {
	return file_arch_proto_rawDescGZIP(), []int{12}
}

func (x *TapesInfo) GetTapes() []*TapeInfo {
	if x != nil {
		return x.Tapes
	}
	return nil
}

type ReplyMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorCode int32  `protobuf:"varint,1,opt,name=errorCode,proto3" json:"errorCode,omitempty"`
	ErrorMsg  string `protobuf:"bytes,2,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
}

func (x *ReplyMsg) Reset() {
	*x = ReplyMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_arch_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReplyMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyMsg) ProtoMessage() {}

func (x *ReplyMsg) ProtoReflect() protoreflect.Message {
	mi := &file_arch_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyMsg.ProtoReflect.Descriptor instead.
func (*ReplyMsg) Descriptor() ([]byte, []int) {
	return file_arch_proto_rawDescGZIP(), []int{13}
}

func (x *ReplyMsg) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *ReplyMsg) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type MigrateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PoolName   string   `protobuf:"bytes,1,opt,name=poolName,proto3" json:"poolName,omitempty"`
	Files      []string `protobuf:"bytes,2,rep,name=files,proto3" json:"files,omitempty"`
	Premigrate bool     `protobuf:"varint,3,opt,name=premigrate,proto3" json:"premigrate,omitempty"`
}

func (x *MigrateRequest) Reset() {
	*x = MigrateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_arch_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MigrateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrateRequest) ProtoMessage() {}

func (x *MigrateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_arch_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrateRequest.ProtoReflect.Descriptor instead.
func (*MigrateRequest) Descriptor() ([]byte, []int) {
	return file_arch_proto_rawDescGZIP(), []int{14}
}

func (x *MigrateRequest) GetPoolName() string {
	if x != nil {
		return x.PoolName
	}
	return ""
}

func (x *MigrateRequest) GetFiles() []string {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *MigrateRequest) GetPremigrate() bool {
	if x != nil {
		return x.Premigrate
	}
	return false
}

type RecallRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resident bool     `protobuf:"varint,1,opt,name=resident,proto3" json:"resident,omitempty"`
	Files    []string `protobuf:"bytes,2,rep,name=files,proto3" json:"files,omitempty"`
}

func (x *RecallRequest) Reset() {
	*x = RecallRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_arch_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecallRequest) ProtoMessage() {}

func (x *RecallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_arch_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecallRequest.ProtoReflect.Descriptor instead.
func (*RecallRequest) Descriptor() ([]byte, []int) {
	return file_arch_proto_rawDescGZIP(), []int{15}
}

func (x *RecallRequest) GetResident() bool {
	if x != nil {
		return x.Resident
	}
	return false
}

func (x *RecallRequest) GetFiles() []string {
	if x != nil {
		return x.Files
	}
	return nil
}

type MigrationStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success     bool  `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ReqNumber   int64 `protobuf:"varint,2,opt,name=reqNumber,proto3" json:"reqNumber,omitempty"`
	Pid         int64 `protobuf:"varint,3,opt,name=pid,proto3" json:"pid,omitempty"`
	Resident    int64 `protobuf:"varint,4,opt,name=resident,proto3" json:"resident,omitempty"`
	Transferred int64 `protobuf:"varint,5,opt,name=transferred,proto3" json:"transferred,omitempty"`
	Premigrated int64 `protobuf:"varint,6,opt,name=premigrated,proto3" json:"premigrated,omitempty"`
	Migrated    int64 `protobuf:"varint,7,opt,name=migrated,proto3" json:"migrated,omitempty"`
	Failed      int64 `protobuf:"varint,8,opt,name=failed,proto3" json:"failed,omitempty"`
	Done        bool  `protobuf:"varint,9,opt,name=done,proto3" json:"done,omitempty"`
}

func (x *MigrationStatus) Reset() {
	*x = MigrationStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_arch_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MigrationStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrationStatus) ProtoMessage() {}

func (x *MigrationStatus) ProtoReflect() protoreflect.Message {
	mi := &file_arch_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrationStatus.ProtoReflect.Descriptor instead.
func (*MigrationStatus) Descriptor() ([]byte, []int) {
	return file_arch_proto_rawDescGZIP(), []int{16}
}

func (x *MigrationStatus) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *MigrationStatus) GetReqNumber() int64 {
	if x != nil {
		return x.ReqNumber
	}
	return 0
}

func (x *MigrationStatus) GetPid() int64 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *MigrationStatus) GetResident() int64 {
	if x != nil {
		return x.Resident
	}
	return 0
}

func (x *MigrationStatus) GetTransferred() int64 {
	if x != nil {
		return x.Transferred
	}
	return 0
}

func (x *MigrationStatus) GetPremigrated() int64 {
	if x != nil {
		return x.Premigrated
	}
	return 0
}

func (x *MigrationStatus) GetMigrated() int64 {
	if x != nil {
		return x.Migrated
	}
	return 0
}

func (x *MigrationStatus) GetFailed() int64 {
	if x != nil {
		return x.Failed
	}
	return 0
}

func (x *MigrationStatus) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

type AsyncStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReqNumber uint64 `protobuf:"varint,1,opt,name=reqNumber,proto3" json:"reqNumber,omitempty"`
}

func (x *AsyncStatusRequest) Reset() {
	*x = AsyncStatusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_arch_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AsyncStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AsyncStatusRequest) ProtoMessage() {}

func (x *AsyncStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_arch_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AsyncStatusRequest.ProtoReflect.Descriptor instead.
func (*AsyncStatusRequest) Descriptor() ([]byte, []int) {
	return file_arch_proto_rawDescGZIP(), []int{17}
}

func (x *AsyncStatusRequest) GetReqNumber() uint64 {
	if x != nil {
		return x.ReqNumber
	}
	return 0
}

type FileInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MigState   string `protobuf:"bytes,1,opt,name=migState,proto3" json:"migState,omitempty"`
	FileName   string `protobuf:"bytes,2,opt,name=fileName,proto3" json:"fileName,omitempty"`
	Size       uint64 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Blocks     uint64 `protobuf:"varint,4,opt,name=blocks,proto3" json:"blocks,omitempty"`
	Fsidh      uint64 `protobuf:"varint,5,opt,name=fsidh,proto3" json:"fsidh,omitempty"`
	Fsidl      uint64 `protobuf:"varint,6,opt,name=fsidl,proto3" json:"fsidl,omitempty"`
	Igen       uint64 `protobuf:"varint,7,opt,name=igen,proto3" json:"igen,omitempty"`
	Inum       uint64 `protobuf:"varint,8,opt,name=inum,proto3" json:"inum,omitempty"`
	TapeId     string `protobuf:"bytes,9,opt,name=tapeId,proto3" json:"tapeId,omitempty"`
	StartBlock uint64 `protobuf:"varint,10,opt,name=startBlock,proto3" json:"startBlock,omitempty"`
}

func (x *FileInfo) Reset() {
	*x = FileInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_arch_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfo) ProtoMessage() {}

func (x *FileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_arch_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfo.ProtoReflect.Descriptor instead.
func (*FileInfo) Descriptor() ([]byte, []int) {
	return file_arch_proto_rawDescGZIP(), []int{18}
}

func (x *FileInfo) GetMigState() string {
	if x != nil {
		return x.MigState
	}
	return ""
}

func (x *FileInfo) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *FileInfo) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileInfo) GetBlocks() uint64 {
	if x != nil {
		return x.Blocks
	}
	return 0
}

func (x *FileInfo) GetFsidh() uint64 {
	if x != nil {
		return x.Fsidh
	}
	return 0
}

func (x *FileInfo) GetFsidl() uint64 {
	if x != nil {
		return x.Fsidl
	}
	return 0
}

func (x *FileInfo) GetIgen() uint64 {
	if x != nil {
		return x.Igen
	}
	return 0
}

func (x *FileInfo) GetInum() uint64 {
	if x != nil {
		return x.Inum
	}
	return 0
}

func (x *FileInfo) GetTapeId() string {
	if x != nil {
		return x.TapeId
	}
	return ""
}

func (x *FileInfo) GetStartBlock() uint64 {
	if x != nil {
		return x.StartBlock
	}
	return 0
}

type FileInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileName string `protobuf:"bytes,1,opt,name=fileName,proto3" json:"fileName,omitempty"`
}

func (x *FileInfoRequest) Reset() {
	*x = FileInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_arch_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfoRequest) ProtoMessage() {}

func (x *FileInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_arch_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfoRequest.ProtoReflect.Descriptor instead.
func (*FileInfoRequest) Descriptor() ([]byte, []int) {
	return file_arch_proto_rawDescGZIP(), []int{19}
}

func (x *FileInfoRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

var File_arch_proto protoreflect.FileDescriptor

var file_arch_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x61, 0x72, 0x63, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22,
	0x25, 0x0a, 0x0f, 0x54, 0x61, 0x70, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x23, 0x0a, 0x0d, 0x54, 0x61, 0x70, 0x65, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x22, 0x72, 0x0a, 0x10, 0x50,
	0x75, 0x74, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x65, 0x75, 0x73, 0x74, 0x12,
	0x18, 0x0a, 0x07, 0x69, 0x73, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x07, 0x69, 0x73, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x72, 0x63,
	0x70, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x72, 0x63, 0x70,
	0x61, 0x74, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x69, 0x6e, 0x61, 0x72,
	0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x62, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x22,
	0x2a, 0x0a, 0x0e, 0x50, 0x75, 0x74, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x65, 0x73, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x64, 0x65, 0x73, 0x70, 0x61, 0x74, 0x68, 0x22, 0x36, 0x0a, 0x08, 0x44,
	0x6d, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x75, 0x6e, 0x6e, 0x69,
	0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x72, 0x75, 0x6e, 0x6e, 0x69, 0x6e,
	0x67, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03,
	0x70, 0x69, 0x64, 0x22, 0x1e, 0x0a, 0x08, 0x50, 0x6f, 0x6f, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x22, 0x82, 0x01, 0x0a, 0x08, 0x50, 0x6f, 0x6f, 0x6c, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6f, 0x6f, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x70, 0x6f, 0x6f, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x72, 0x65, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x04, 0x66, 0x72, 0x65, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x75, 0x6e, 0x72, 0x65, 0x66, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x75, 0x6e, 0x72, 0x65, 0x66, 0x12, 0x1a, 0x0a, 0x08,
	0x6e, 0x75, 0x6d, 0x74, 0x61, 0x70, 0x65, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08,
	0x6e, 0x75, 0x6d, 0x74, 0x61, 0x70, 0x65, 0x73, 0x22, 0x35, 0x0a, 0x09, 0x50, 0x6f, 0x6f, 0x6c,
	0x73, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x28, 0x0a, 0x05, 0x70, 0x6f, 0x6f, 0x6c, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x50, 0x6f, 0x6f, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x70, 0x6f, 0x6f, 0x6c, 0x73, 0x22,
	0x76, 0x0a, 0x0a, 0x44, 0x72, 0x69, 0x76, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x18, 0x0a,
	0x07, 0x64, 0x65, 0x76, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x64, 0x65, 0x76, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x6c, 0x6f, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x73, 0x6c, 0x6f, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x75, 0x73, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x04, 0x62, 0x75, 0x73, 0x79, 0x22, 0x3d, 0x0a, 0x0b, 0x44, 0x72, 0x69, 0x76, 0x65,
	0x72, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x2e, 0x0a, 0x07, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x44, 0x72, 0x69, 0x76, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x64,
	0x72, 0x69, 0x76, 0x65, 0x72, 0x73, 0x22, 0xec, 0x01, 0x0a, 0x08, 0x54, 0x61, 0x70, 0x65, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x6c, 0x6f, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x04, 0x73, 0x6c, 0x6f, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x63, 0x61, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x63, 0x61, 0x70, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x63, 0x61, 0x70,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x72, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x63, 0x61,
	0x70, 0x12, 0x20, 0x0a, 0x0b, 0x72, 0x65, 0x63, 0x6c, 0x61, 0x69, 0x6d, 0x61, 0x62, 0x6c, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0b, 0x72, 0x65, 0x63, 0x6c, 0x61, 0x69, 0x6d, 0x61,
	0x62, 0x6c, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x69,
	0x6e, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x0a, 0x69, 0x6e, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x70,
	0x6f, 0x6f, 0x6c, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x6f, 0x6f, 0x6c, 0x12,
	0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x73, 0x74, 0x61, 0x74, 0x65, 0x22, 0x35, 0x0a, 0x09, 0x54, 0x61, 0x70, 0x65, 0x73, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x28, 0x0a, 0x05, 0x74, 0x61, 0x70, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x61, 0x70,
	0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x74, 0x61, 0x70, 0x65, 0x73, 0x22, 0x44, 0x0a, 0x08,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x4d, 0x73, 0x67, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d,
	0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d,
	0x73, 0x67, 0x22, 0x62, 0x0a, 0x0e, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6f, 0x6f, 0x6c, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6f, 0x6f, 0x6c, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x05, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x72, 0x65, 0x6d, 0x69, 0x67,
	0x72, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x70, 0x72, 0x65, 0x6d,
	0x69, 0x67, 0x72, 0x61, 0x74, 0x65, 0x22, 0x41, 0x0a, 0x0d, 0x52, 0x65, 0x63, 0x61, 0x6c, 0x6c,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x69, 0x64,
	0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x72, 0x65, 0x73, 0x69, 0x64,
	0x65, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x05, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x22, 0x83, 0x02, 0x0a, 0x0f, 0x4d, 0x69,
	0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a,
	0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x71, 0x4e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x72, 0x65, 0x71, 0x4e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x03, 0x70, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x69, 0x64,
	0x65, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x72, 0x65, 0x73, 0x69, 0x64,
	0x65, 0x6e, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x72,
	0x65, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66,
	0x65, 0x72, 0x72, 0x65, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x72, 0x65, 0x6d, 0x69, 0x67, 0x72,
	0x61, 0x74, 0x65, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x70, 0x72, 0x65, 0x6d,
	0x69, 0x67, 0x72, 0x61, 0x74, 0x65, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x6d, 0x69, 0x67, 0x72, 0x61,
	0x74, 0x65, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x6d, 0x69, 0x67, 0x72, 0x61,
	0x74, 0x65, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x66, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x64,
	0x6f, 0x6e, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x64, 0x6f, 0x6e, 0x65, 0x22,
	0x32, 0x0a, 0x12, 0x41, 0x73, 0x79, 0x6e, 0x63, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x71, 0x4e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x72, 0x65, 0x71, 0x4e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x22, 0xfa, 0x01, 0x0a, 0x08, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x1a, 0x0a, 0x08, 0x6d, 0x69, 0x67, 0x53, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x6d, 0x69, 0x67, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x66, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x66, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x62, 0x6c,
	0x6f, 0x63, 0x6b, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x73, 0x69, 0x64, 0x68, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x05, 0x66, 0x73, 0x69, 0x64, 0x68, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x73,
	0x69, 0x64, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x66, 0x73, 0x69, 0x64, 0x6c,
	0x12, 0x12, 0x0a, 0x04, 0x69, 0x67, 0x65, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04,
	0x69, 0x67, 0x65, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x6e, 0x75, 0x6d, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x04, 0x69, 0x6e, 0x75, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x61, 0x70, 0x65,
	0x49, 0x64, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x70, 0x65, 0x49, 0x64,
	0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x0a,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b,
	0x22, 0x2d, 0x0a, 0x0f, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x32,
	0xb6, 0x07, 0x0a, 0x0a, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76, 0x61, 0x6c, 0x65, 0x72, 0x12, 0x43,
	0x0a, 0x0b, 0x47, 0x65, 0x74, 0x54, 0x61, 0x70, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x19, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x61, 0x70, 0x65, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x54, 0x61, 0x70, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x22, 0x00, 0x12, 0x43, 0x0a, 0x09, 0x50, 0x75, 0x74, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74,
	0x12, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x50, 0x75, 0x74, 0x4f,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x65, 0x75, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x50, 0x75, 0x74, 0x4f, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x34, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x44,
	0x6d, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x44, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x00, 0x12, 0x36,
	0x0a, 0x0c, 0x47, 0x65, 0x74, 0x50, 0x6f, 0x6f, 0x6c, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0f,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a,
	0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x50, 0x6f, 0x6f, 0x6c, 0x73,
	0x49, 0x6e, 0x66, 0x6f, 0x22, 0x00, 0x12, 0x3a, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x44, 0x72, 0x69,
	0x76, 0x65, 0x72, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x44, 0x72, 0x69, 0x76, 0x65, 0x72, 0x73, 0x49, 0x6e, 0x66, 0x6f,
	0x22, 0x00, 0x12, 0x36, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x54, 0x61, 0x70, 0x65, 0x73, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x1a, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54,
	0x61, 0x70, 0x65, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x00, 0x12, 0x36, 0x0a, 0x0a, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x6f, 0x6c, 0x12, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x50, 0x6f, 0x6f, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x1a, 0x12, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x4d, 0x73, 0x67,
	0x22, 0x00, 0x12, 0x36, 0x0a, 0x0a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x6f, 0x6f, 0x6c,
	0x12, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x50, 0x6f, 0x6f, 0x6c,
	0x4e, 0x61, 0x6d, 0x65, 0x1a, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x4d, 0x73, 0x67, 0x22, 0x00, 0x12, 0x40, 0x0a, 0x07, 0x4d, 0x69,
	0x67, 0x72, 0x61, 0x74, 0x65, 0x12, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4d, 0x69, 0x67, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x00, 0x12, 0x3e, 0x0a, 0x06,
	0x52, 0x65, 0x63, 0x61, 0x6c, 0x6c, 0x12, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x52, 0x65, 0x63, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4d, 0x69, 0x67, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x00, 0x12, 0x31, 0x0a, 0x08,
	0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x12, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x4d, 0x73, 0x67, 0x22, 0x00, 0x12,
	0x45, 0x0a, 0x0c, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x65, 0x41, 0x73, 0x79, 0x6e, 0x63, 0x12,
	0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4d, 0x69, 0x67, 0x72, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x22, 0x00, 0x12, 0x43, 0x0a, 0x0b, 0x52, 0x65, 0x63, 0x61, 0x6c, 0x6c,
	0x41, 0x73, 0x79, 0x6e, 0x63, 0x12, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x52, 0x65, 0x63, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x00, 0x12, 0x4b, 0x0a, 0x0e, 0x47,
	0x65, 0x74, 0x41, 0x73, 0x79, 0x6e, 0x63, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1c, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x73, 0x79, 0x6e, 0x63, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x00, 0x12, 0x3e, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x46,
	0x69, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x46, 0x69,
	0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x00, 0x42, 0x0d, 0x5a, 0x0b, 0x2e, 0x2f, 0x3b, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_arch_proto_rawDescOnce sync.Once
	file_arch_proto_rawDescData = file_arch_proto_rawDesc
)

func file_arch_proto_rawDescGZIP() []byte {
	file_arch_proto_rawDescOnce.Do(func() {
		file_arch_proto_rawDescData = protoimpl.X.CompressGZIP(file_arch_proto_rawDescData)
	})
	return file_arch_proto_rawDescData
}

var file_arch_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_arch_proto_goTypes = []interface{}{
	(*Empty)(nil),              // 0: protobuf.Empty
	(*TapeInfoRequest)(nil),    // 1: protobuf.TapeInfoRequest
	(*TapeInfoReply)(nil),      // 2: protobuf.TapeInfoReply
	(*PutObjectReqeust)(nil),   // 3: protobuf.PutObjectReqeust
	(*PutObjectReply)(nil),     // 4: protobuf.PutObjectReply
	(*DmStatus)(nil),           // 5: protobuf.DmStatus
	(*PoolName)(nil),           // 6: protobuf.PoolName
	(*PoolInfo)(nil),           // 7: protobuf.PoolInfo
	(*PoolsInfo)(nil),          // 8: protobuf.PoolsInfo
	(*DriverInfo)(nil),         // 9: protobuf.DriverInfo
	(*DriversInfo)(nil),        // 10: protobuf.DriversInfo
	(*TapeInfo)(nil),           // 11: protobuf.TapeInfo
	(*TapesInfo)(nil),          // 12: protobuf.TapesInfo
	(*ReplyMsg)(nil),           // 13: protobuf.ReplyMsg
	(*MigrateRequest)(nil),     // 14: protobuf.MigrateRequest
	(*RecallRequest)(nil),      // 15: protobuf.RecallRequest
	(*MigrationStatus)(nil),    // 16: protobuf.MigrationStatus
	(*AsyncStatusRequest)(nil), // 17: protobuf.AsyncStatusRequest
	(*FileInfo)(nil),           // 18: protobuf.FileInfo
	(*FileInfoRequest)(nil),    // 19: protobuf.FileInfoRequest
}
var file_arch_proto_depIdxs = []int32{
	7,  // 0: protobuf.PoolsInfo.pools:type_name -> protobuf.PoolInfo
	9,  // 1: protobuf.DriversInfo.drivers:type_name -> protobuf.DriverInfo
	11, // 2: protobuf.TapesInfo.tapes:type_name -> protobuf.TapeInfo
	1,  // 3: protobuf.Archivaler.GetTapeInfo:input_type -> protobuf.TapeInfoRequest
	3,  // 4: protobuf.Archivaler.PutObject:input_type -> protobuf.PutObjectReqeust
	0,  // 5: protobuf.Archivaler.GetDmStatus:input_type -> protobuf.Empty
	0,  // 6: protobuf.Archivaler.GetPoolsInfo:input_type -> protobuf.Empty
	0,  // 7: protobuf.Archivaler.GetDriversInfo:input_type -> protobuf.Empty
	0,  // 8: protobuf.Archivaler.GetTapesInfo:input_type -> protobuf.Empty
	6,  // 9: protobuf.Archivaler.CreatePool:input_type -> protobuf.PoolName
	6,  // 10: protobuf.Archivaler.DeletePool:input_type -> protobuf.PoolName
	14, // 11: protobuf.Archivaler.Migrate:input_type -> protobuf.MigrateRequest
	15, // 12: protobuf.Archivaler.Recall:input_type -> protobuf.RecallRequest
	0,  // 13: protobuf.Archivaler.Retrieve:input_type -> protobuf.Empty
	14, // 14: protobuf.Archivaler.MigrateAsync:input_type -> protobuf.MigrateRequest
	15, // 15: protobuf.Archivaler.RecallAsync:input_type -> protobuf.RecallRequest
	17, // 16: protobuf.Archivaler.GetAsyncStatus:input_type -> protobuf.AsyncStatusRequest
	19, // 17: protobuf.Archivaler.GetFileInfo:input_type -> protobuf.FileInfoRequest
	2,  // 18: protobuf.Archivaler.GetTapeInfo:output_type -> protobuf.TapeInfoReply
	4,  // 19: protobuf.Archivaler.PutObject:output_type -> protobuf.PutObjectReply
	5,  // 20: protobuf.Archivaler.GetDmStatus:output_type -> protobuf.DmStatus
	8,  // 21: protobuf.Archivaler.GetPoolsInfo:output_type -> protobuf.PoolsInfo
	10, // 22: protobuf.Archivaler.GetDriversInfo:output_type -> protobuf.DriversInfo
	12, // 23: protobuf.Archivaler.GetTapesInfo:output_type -> protobuf.TapesInfo
	13, // 24: protobuf.Archivaler.CreatePool:output_type -> protobuf.ReplyMsg
	13, // 25: protobuf.Archivaler.DeletePool:output_type -> protobuf.ReplyMsg
	16, // 26: protobuf.Archivaler.Migrate:output_type -> protobuf.MigrationStatus
	16, // 27: protobuf.Archivaler.Recall:output_type -> protobuf.MigrationStatus
	13, // 28: protobuf.Archivaler.Retrieve:output_type -> protobuf.ReplyMsg
	16, // 29: protobuf.Archivaler.MigrateAsync:output_type -> protobuf.MigrationStatus
	16, // 30: protobuf.Archivaler.RecallAsync:output_type -> protobuf.MigrationStatus
	16, // 31: protobuf.Archivaler.GetAsyncStatus:output_type -> protobuf.MigrationStatus
	18, // 32: protobuf.Archivaler.GetFileInfo:output_type -> protobuf.FileInfo
	18, // [18:33] is the sub-list for method output_type
	3,  // [3:18] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_arch_proto_init() }
func file_arch_proto_init() {
	if File_arch_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_arch_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_arch_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TapeInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_arch_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TapeInfoReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_arch_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PutObjectReqeust); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_arch_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PutObjectReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_arch_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DmStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_arch_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PoolName); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_arch_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PoolInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_arch_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PoolsInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_arch_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DriverInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_arch_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DriversInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_arch_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TapeInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_arch_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TapesInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_arch_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReplyMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_arch_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MigrateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_arch_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecallRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_arch_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MigrationStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_arch_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AsyncStatusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_arch_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_arch_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_arch_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_arch_proto_goTypes,
		DependencyIndexes: file_arch_proto_depIdxs,
		MessageInfos:      file_arch_proto_msgTypes,
	}.Build()
	File_arch_proto = out.File
	file_arch_proto_rawDesc = nil
	file_arch_proto_goTypes = nil
	file_arch_proto_depIdxs = nil
}
