version: '3.9'

services:
  master:
    image: jibutech-registry.cn-hangzhou.cr.aliyuncs.com/udm/seaweedfs:3.68.9-dev
    network_mode: "host"
    ports:
      - 9333:9333
      - 19333:19333
    command: "master -ip=192.168.4.249 -volumeSizeLimitMB=4096 -defaultReplication=000"
    restart: unless-stopped
  volume1:
    image: jibutech-registry.cn-hangzhou.cr.aliyuncs.com/udm/seaweedfs:3.68.9-dev
    network_mode: "host"
    ports:
      - 7455:8080
      - 9325:9325
    volumes:
      - /mnt/weed1:/mnt/weed1
      - /var/log/udm:/var/log/udm
    command: 'volume -dir=/mnt/weed1 -mserver="localhost:9333" -max=0 -port=8080 -metricsPort=9325 -preStopSeconds=1'
    depends_on:
      - master
    restart: unless-stopped
  volume2:
    image: jibutech-registry.cn-hangzhou.cr.aliyuncs.com/udm/seaweedfs:3.68.9-dev
    network_mode: "host"
    ports:
      - 7456:8081
      - 9326:9326
    volumes:
      - /mnt/weed2:/mnt/weed2
      - /var/log/udm:/var/log/udm
    command: 'volume -dir=/mnt/weed2 -mserver="localhost:9333" -max=0 -port=8081 -metricsPort=9326 -preStopSeconds=1'
    depends_on:
      - master
    restart: unless-stopped
  s3:
    image: jibutech-registry.cn-hangzhou.cr.aliyuncs.com/udm/seaweedfs:3.68.9-dev
    network_mode: "host"
    ports:
      - 8888:8888
      - 18888:18888
      - 8333:8333
    command: '-logdir=/var/log/udm filer -master="master:9333" -s3 -s3.config=/etc/seaweedfs/s3.json -s3.port=8333 -s3.allowEmptyFolder=false -s3.allowDeleteBucketNotEmpty=false'
    volumes:
      - /var/log/udm:/var/log/udm
      - ./udm-s3.json:/etc/seaweedfs/s3.json
    depends_on:
      - master
      - volume1
      - volume2
  minio-gateway-s3:
    image: registry.cn-shanghai.aliyuncs.com/ys1000/minio:2021.12.10-debian-11-r0
    network_mode: "host"
    ports:
      - 9000:9000
    command: 'minio gateway s3 http://192.168.4.249:8333'
    restart: on-failure
    environment:
      MINIO_ROOT_USER: udm_admin
      MINIO_ROOT_PASSWORD: udm_passw0rd
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    depends_on:
      - s3